# Generated by Django 3.2.1 on 2022-05-11 11:28

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220511_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_address', models.CharField(max_length=200)),
                ('toll_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='card_uid',
            field=models.CharField(max_length=20, unique=True, validators=[account.validators.validate_hex]),
        ),
    ]
