# Generated by Django 3.2.1 on 2022-05-13 10:00

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220511_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_uid',
            field=models.CharField(max_length=10, unique=True, validators=[account.validators.validate_decimal]),
        ),
    ]
