# Generated by Django 3.2.1 on 2022-05-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_card_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, default='2022-05-13'),
            preserve_default=False,
        ),
    ]
